# Custom Language File for Launcher Customizer

[ejs.app]
title = "샘플런처"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/demoLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaAfreecaTVURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/demoLauncher"
supportLink = "https://github.com/CustomLauncherLab/demoLauncher/issues"

[ejs.welcome]
welcomeHeader = "샘플런처"
welcomeDescription = "첫째 줄.<br>둘째 줄.<br>셋째줄."
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."